/**
 * Algorithm Instantiation Architecture
 * 
 * This module defines the core types used in the algorithm instantiation system.
 * It enables LLMs to define algorithms that can be executed by specialized agents.
 */

/**
 * Represents the schema for algorithm inputs and outputs
 */
export interface JSONSchema {
  type: string;
  properties?: Record<string, {
    type: string;
    description?: string;
    items?: any;
    additionalProperties?: boolean;
  }>;
  required?: string[];
  additionalProperties?: boolean;
}

/**
 * Represents a parameter for an algorithm
 */
export interface AlgorithmParameter {
  name: string;
  description: string;
  type: 'string' | 'number' | 'boolean' | 'object' | 'array';
  default?: any;
  required: boolean;
  constraints?: string[];
}

/**
 * Represents a complete algorithm definition generated by an LLM
 */
export interface AlgorithmDefinition {
  id?: string;
  name: string;
  description: string;
  implementation: string; 
  language?: 'javascript' | 'python' | 'sql';
  inputSchema: JSONSchema;
  outputSchema: JSONSchema;
  parameters?: AlgorithmParameter[];
  tags?: string[];
  sampleData?: any;
  executorConfig?: Record<string, any>;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Represents the result of an algorithm execution
 */
export interface AlgorithmExecutionResult {
  success: boolean;
  output?: any;
  error?: string;
  executionTime?: number; 
  resourceUsage?: {
    memory?: number; 
    cpu?: number; 
  };
  logs?: string[];
  algorithm?: AlgorithmDefinition;
  algorithmId?: string;
  executionRecordId?: string;
}

/**
 * Represents a request to execute an algorithm
 */
export interface AlgorithmExecutionRequest {
  algorithmId?: string;
  algorithmDefinition?: AlgorithmDefinition;
  inputs: Record<string, any>;
  timeout?: number; // ms
  executionId?: string;
}

/**
 * Represents the available algorithm executor types
 */
export type ExecutorType = 'python' | 'javascript' | 'sql';
