
export type MessageType = 'user' | 'agent' | 'system' | 'analysis_result' | 'data_upload';

export interface EnhancedMessage {
  id: string;
  conversation_id: string;
  sender_type: 'user' | 'agent' | 'system';
  sender_id: string | null;
  content: string;
  metadata?: any;
  created_at: string;
  message_type?: MessageType;
  system_category?: 'analysis' | 'data_processing' | 'method_selection' | 'interpretation';
}

export const categorizeMessage = (content: string, senderType: string): MessageType => {
  if (senderType === 'user') return 'user';
  
  // Check for analysis result patterns
  if (content.includes('Analysis Complete') || 
      content.includes('Statistical Analysis Results') ||
      content.includes('Method:') ||
      content.includes('Seasonality Analysis')) {
    return 'analysis_result';
  }
  
  // Check for data upload related messages
  if (content.includes('upload') || content.includes('CSV') || content.includes('data file')) {
    return 'data_upload';
  }
  
  // Check for system messages
  if (content.includes('MoLAS') || content.includes('Pipeline') || content.includes('Discovery Module')) {
    return 'system';
  }
  
  return 'agent';
};

export const getSystemCategory = (content: string): 'analysis' | 'data_processing' | 'method_selection' | 'interpretation' | undefined => {
  if (content.includes('STL') || content.includes('method') || content.includes('selected')) {
    return 'method_selection';
  }
  if (content.includes('Analysis Complete') || content.includes('results')) {
    return 'analysis';
  }
  if (content.includes('interpretation') || content.includes('insights')) {
    return 'interpretation';
  }
  if (content.includes('data') || content.includes('processing')) {
    return 'data_processing';
  }
  return undefined;
};

export const formatAnalysisResult = (result: any): string => {
  return `🔍 **Seasonality Analysis Complete**

**Method**: ${result.method}
**Data Quality**: ${result.dataQuality || 'Good'}

**Summary**: ${result.summary}

**Key Insights**:
${result.insights?.map((insight: string) => `• ${insight}`).join('\n') || '• Analysis completed successfully'}

**Recommendations**:
${result.recommendations?.map((rec: string) => `• ${rec}`).join('\n') || '• Review the generated visualizations'}

${result.statisticalMetrics ? `
**Statistical Metrics**:
• Mean: ${result.statisticalMetrics.mean?.toFixed(2)}
• Trend Slope: ${result.statisticalMetrics.trendSlope?.toFixed(4)}
• Seasonality Strength: ${(result.statisticalMetrics.seasonalityStrength * 100)?.toFixed(1)}%
` : ''}

*This analysis was generated by the MoLAS pipeline using real statistical calculations.*`;
};
